### ISSUE TITLE
Not working when triggered from HomeBridge

### ISSUE THREAD

**Issue by llajas** [ToracX/homebridge-dreamscreen#1]
Hello!

I’m unable to utilize the plugin. I’ve added my 4K unit to the config and I can see it successfully in HomeBridge as well as Home app, however when I attempt to take any action, nothing happens on my DS. Logs show the commands are being sent but no response is observed on my DS.

I can confirm that I was able to use the HomeBridge terminal to manually use the python script with success (‘homebridge/node_modules/homebridge-dreamscreen # python dreamscreen.py -i 10.0.0.20 -m 1’) so I believe the issue is somewhere between the script and how HomeBridge is being called.

I have a static assignment for my DreamScreen in my router, so IP is not the issue, as manually using the script works with the ‘-m 1’ & ‘-m 0’ options. 

Any thoughts? Appreciate your time in advance.

**Comment by ToracX** [comment]
Hey,

My apologies for my late reply, busy weekend.
I made changes to the index.js that should solve you're problem.
You can delete the old plugin folder and reinstall it with git clone.
Make sure **not** to update with NPM because I have not yet made the changes on that platform, only on this github repo.
Or you can just copy and paste the new index.js.

Please provide feedback whether the changes were succesfull or not. :)

Greetings,
Torac

**Comment by llajas** [comment]
No worries! Thanks for taking time to reply and investigate! I've updated my index.js and that has solved the issue - I can control the accessory from Homekit now! (And even better, via Siri!) :)

Safe to mark this as solved! Hopefully in the future, an option can be included that will allow to switch across the inputs on the DS. Thanks again!!!

**Comment by ToracX** [comment]
Great to hear!
How would you see such an feature implemented? Personally I don’t use more than 1 hdmi port. What kind of accessory would want to use? An separate TV accessory or more switches?
If I have more time this week I could take a look at port switching.
